spring:
  application:
    name: order
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/springcloud_sell?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false
    username: root
    password: root123
  rabbitmq:
    host: 10.20.21.136
    port: 5672
    username: wangjie
    password: wangjie
  redis:
    host: 10.20.21.136
    port: 6379
    password: redis  
env:
  test10
feign:
  client:
    config: 
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic
